# Generated by Django 4.2.4 on 2023-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0002_editora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editora",
            name="nome",
            field=models.CharField(max_length=150),
        ),
    ]
